# Generated by Django 3.0.7 on 2020-12-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20201203_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='цена'),
            preserve_default=False,
        ),
    ]
