# Generated by Django 3.0.7 on 2020-12-03 15:48

from django.db import migrations


def set_price_for_order_item(apps, schema_editor):
    Item = apps.get_model('foodcartapp', 'Item') # noqa
    for item in Item.objects.all():
        item.cost = item.quantity * item.product.price
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_item_cost'),
    ]

    operations = [
        migrations.RunPython(set_price_for_order_item),
    ]
