# Generated by Django 3.0.7 on 2020-12-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20201203_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Необработанный'), ('processing', 'Обрабатывается'), ('collected', 'Собран'), ('done', 'Выполнен')], default='new', max_length=100, verbose_name='статус'),
        ),
    ]
