# Generated by Django 3.0.7 on 2020-12-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20201203_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_method',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('card', 'Электронно')], default='cash', max_length=50, verbose_name='способ оплаты'),
        ),
    ]
